# ✅ Basic Config
owner: Logulokesh
repo: StatusMonitor

# ✅ Monitored Services
sites:
  - name: Ollama
    url: https://ollama.logu.au
  - name: Apache Spark
    url: https://spark.logu.au
  - name: Apache Airflow
    url: https://airflow.logu.au
  - name: Langfuse
    url: https://langfuse.logu.au
  - name: Airbyte
    url: https://airbyte.logu.au
  - name: Apache Kafka
    url: https://kafka.logu.au
  - name: MinIO
    url: https://minio.logu.au
  - name: Trino
    url: https://trino.logu.au
  - name: Metabase
    url: https://metabase.logu.au
  - name: Nginx Proxy Manager
    url: https://nginx.logu.au
  - name: HashiCorp Vault
    url: https://vault.logu.au
  - name: Portainer
    url: https://portainer.logu.au
  - name: Grafana
    url: https://grafana.logu.au
  - name: Prometheus
    url: https://prometheus.logu.au
  - name: Uptime Kuma
    url: https://uptimekuma.logu.au
  - name: Traccar
    url: https://traccar.logu.au
  - name: n8n
    url: https://n8n.logu.au
  - name: Jellyfin
    url: https://music.logu.au

# ✅ Status Website Configuration
status-website:
  cname: status.logu.au  # Optional: Set this if you plan to use a custom domain
  # baseUrl: /StatusMonitor  # Uncomment only if you don’t use a custom domain
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: KinAI Status Monitor
  introTitle: "📡 KinAI Status Dashboard"
  introMessage: |
    Monitoring 20+ critical services for KinAI — real-time insights, zero servers. 
    Powered by GitHub Actions, Issues, and Pages. [**Build yours**](https://github.com/upptime/upptime)

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Logulokesh/StatusMonitor
